version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json
      - ./output:/app/dist/output
    command: >
      /bin/sh -c "cp /app/dist/main /app/dist/output/"