name: Release Executable

on:
  push:
    tags:
      - "*"
permissions:
    packages: write
    contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.RELEAST_TOKEN }}
        with:
          title: Release ${{ github.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: class_backup

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEAST_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/class_backup
          asset_name: class_backup
          asset_content_type: application/octet-stream