name: Release Executable

on:
  release:
    types: [created]

permissions:
    packages: write
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shc
        run: sudo apt-get install shc

      - name: Encrypt backup.sh
        run: shc -r -v -f backup.sh

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEAST_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./backup.sh.x
          asset_name: backup.bin
          asset_content_type: application/octet-stream
          
      - name: Upload config.json as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEAST_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./config.json
          asset_name: config.json
          asset_content_type: application/json
